# Generated by Django 4.2.5 on 2023-11-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0002_alter_customers_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='cart_user',
        ),
    ]
