# Generated by Django 4.2.5 on 2023-11-05 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_api', '0003_rename_user_cart_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
