# Generated by Django 4.2.5 on 2023-11-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0004_alter_cart_cart_user_delete_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='Buy', max_length=10),
        ),
    ]
